[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "bfm"
version = "0.1.0"
description = "Tools for Brain Foundation Models"
authors = [
    { name = "Andrii Zahorodnii", email = "zaho@mit.edu" }
]
license = "MIT"
license-files = ["LICENSE"]
readme = "README.md"

dependencies = [
    "h5py",
    "joblib",
    "librosa",
    "matplotlib",
    "numpy",
    "pandas",
    "psutil",
    "python-dotenv",
    "scikit-learn",
    "scipy",
    "seaborn",
    "torch",
    "torchvision",
    "torchaudio",
    "wandb",
    "mne",
    "tqdm",
    "mne_bids"
]

[project.optional-dependencies]
dev = [
    "requests",
    "beautifulsoup4",
    "ipykernel",
    "jupyter",
    "pytest",
    "ruff",
]

docs = [    
    "mkdocs",
    "mkdocs-jupyter",
    "mkdocs-material", 
    "mkdocstrings[python]"
]

[tool.setuptools.packages.find]
where = ["."]

[tool.pytest.ini_options]
testpaths = ["tests"]
markers = [
    "needs_autodiscover: marks tests that require registry autodiscovery"
]
